# numpy-array-operations

Use the "Run" button to execute the code.

In [1]:
import numpy as np

In [2]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [3]:
print(arr1)
print(arr2)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [4]:
function1= np.concatenate((arr1, arr2), axis=0)

In [5]:
print(function1)

[ 1  2  3  4  5  6  7  8  9 10]


In [6]:
#example 2
arr3 = np.array([[1,2,3], [4,5,6]])
print(arr3)

[[1 2 3]
 [4 5 6]]


In [7]:
arr4 = np.array([[123], [456]])

In [8]:
print(arr4)

[[123]
 [456]]


In [9]:
function2 = np.concatenate((arr3, arr4), axis=1)
print(function2)

[[  1   2   3 123]
 [  4   5   6 456]]


In [10]:
#example 3
arr5 = np.array([[[1, 2, 3], 
                  [4, 5, 6]], 
                 [[1, 2, 3], 
                  [4, 5, 6]]])

In [11]:
arr5.dtype

dtype('int32')

In [12]:
arr5.shape

(2, 2, 3)

In [13]:
arr6 = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [7, 8, 9]]])

In [14]:
print(arr6)

[[[1 2 3]
  [4 5 6]]

 [[1 2 3]
  [7 8 9]]]


In [15]:
function3 = np.concatenate((arr5, arr6), axis=1)

In [16]:
print(function3)

[[[1 2 3]
  [4 5 6]
  [1 2 3]
  [4 5 6]]

 [[1 2 3]
  [4 5 6]
  [1 2 3]
  [7 8 9]]]


In [17]:
a = np.array(42)
b = np.array([1, 2, 3, 4, 5])
c = np.array([[1, 2, 3], [4, 5, 6]])
d = np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

print(a.ndim)
print(b.ndim)
print(c.ndim)
print(d.ndim)

0
1
2
3


In [18]:
import urllib.request

urllib.request.urlretrieve(
    'https://gist.github.com/BirajCoder/a4ffcb76fd6fb221d76ac2ee2b8584e9/raw/4054f90adfd361b7aa4255e99c2e874664094cea/climate.csv', 
    'climate.txt')

('climate.txt', <http.client.HTTPMessage at 0x17945a57850>)

In [19]:
climate_data = np.genfromtxt('climate.txt', delimiter=',', skip_header=1)

In [20]:
climate_data

array([[25., 76., 99.],
       [39., 65., 70.],
       [59., 45., 77.],
       ...,
       [99., 62., 58.],
       [70., 71., 91.],
       [92., 39., 76.]])

In [21]:
climate_data.shape


(10000, 3)

In [22]:
weights = np.array([0.3, 0.2, 0.5])

In [23]:
yields = climate_data @ weights

In [24]:
yields

array([72.2, 59.7, 65.2, ..., 71.1, 80.7, 73.4])

In [25]:
climate_results = np.concatenate((climate_data, yields.reshape(10000, 1)), axis=1)

In [26]:
climate_results

array([[25. , 76. , 99. , 72.2],
       [39. , 65. , 70. , 59.7],
       [59. , 45. , 77. , 65.2],
       ...,
       [99. , 62. , 58. , 71.1],
       [70. , 71. , 91. , 80.7],
       [92. , 39. , 76. , 73.4]])

In [27]:
np.savetxt('climate_results.txt', 
           climate_results, 
           fmt='%.2f', 
           delimiter=',',
           header='temperature,rainfall,humidity,yeild_apples', 
           comments='')

In [28]:
function4 = np.concatenate((climate_data, climate_results), axis=1)

In [29]:
print(function4)

[[25.  76.  99.  ... 76.  99.  72.2]
 [39.  65.  70.  ... 65.  70.  59.7]
 [59.  45.  77.  ... 45.  77.  65.2]
 ...
 [99.  62.  58.  ... 62.  58.  71.1]
 [70.  71.  91.  ... 71.  91.  80.7]
 [92.  39.  76.  ... 39.  76.  73.4]]
